name: 'Build Docker image'
description: 'Build (and optionally push) the Docker image'
inputs:
  version:
    required: true
    description: 'Version for the new image built'
  push:
    required: false
    description: 'Push the built image to Github CR'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: 'Build Docker image'
      id: buildDockerImage
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: ${{ inputs.push }}
        tags: ghcr.io/${{ github.repository }}:${{ inputs.version }}
        build-args: |
          CLI_VERSION=${{ inputs.version }}
    - name: 'Image digest'
      run: echo ${{ steps.buildDockerImage.outputs.digest }}
      shell: bash
