name: CI
on: [push, pull_request]

jobs:
  runTests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    container: node:16.16-alpine3.16
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Install npm deps'
        run: npm ci
      - name: 'Build the CLI'
        run: npm run build
      - name: 'Run tests'
        run: npm run tests
  buildDockerImage:
    name: 'Build Docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: shortSha
        with:
          length: 8
      - name: 'Build Docker image'
        uses: ./.github/actions/build-docker-image
        with:
          version: ${{ steps.shortSha.outputs.sha }}
      - name: 'Run Trivy scans'
        uses: ./.github/actions/run-trivy-scans
        with:
          image-version: ${{ steps.shortSha.outputs.sha }}
