name: CI
on: [push, pull_request]

jobs:
  buildDockerImage:
    name: 'Build Docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - uses: ./.github/actions/build-docker-image
        with:
          version: ${{ github.sha }}
