name: CI
on: [push, pull_request]

jobs:
  buildDockerImage:
    name: 'Build Docker image'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Build Docker image'
        id: buildDockerImage
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: 'Image digest'
        run: echo ${{ steps.buildDockerImage.outputs.digest }}
