name: Release
on: [push, pull_request]

jobs:
  buildImage:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2
      - name: "Login to GitHub CR"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push to GitHub CR"
        id: buildAndPush
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}:0.1.0-alpha1
      - name: "Image digest"
        run: echo ${{ steps.buildAndPush.outputs.digest }}
