name: Release
on:
  push:
    tags:
      - '*'

jobs:
  releaseOnGHCR:
    name: 'Release on GitHub CR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Get tag'
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: 'Login to GitHub CR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build and push to GitHub CR'
        id: buildAndPush
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.tag }}
          build-args: |
            CLI_VERSION=${{ steps.tag.outputs.tag }}
      - name: 'Image digest'
        run: echo ${{ steps.buildAndPush.outputs.digest }}
