name: Release
on:
  push:
    tags:
      - '*'

jobs:
  releaseOnGHCR:
    name: 'Release on GitHub CR'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2
      - name: 'Get tag'
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: 'Login to GitHub CR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/build-docker-image
        with:
          version: ${{ steps.tag.outputs.tag }}
          puh: true
